version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.6.1
        context:
          - top-forum-backend
        environment:
          DB_USERNAME: ${DB_USERNAME}
          DB_PASSWORD: ${DB_PASSWORD}
          TEST_DB: ${TEST_DB}
          DB_HOST: ${DB_HOST}
          APP_HOST: ${APP_HOST}
          MAIL_HOST: ${MAIL_HOST}
          MAIL_PORT: ${MAIL_PORT}
          MAIL_USER: ${MAIL_USER}
          MAIL_PASSWORD: ${MAIL_PASSWORD}
          MAIL_DEFAULT: ${MAIL_DEFAULT}
          JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
          JWT_EXPIRATION: ${JWT_EXPIRATION}
      - image: cimg/postgres:15.3
        context:
          - top-forum-backend
        environment:
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${TEST_DB}

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: npm install sequelize-cli

      - run: npm test
