version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:latest
        environment:
          DB_USERNAME: postgres
          DB_PASSWORD: 1234
          TEST_DB: top_forum_test_db
          DB_HOST: localhost
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: top_forum_test_db

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: npm test
